name: Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile WHITELIST-DB.py

      - name: Get Version from version.txt
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Upload Executable as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets{?name,label}"
          asset_path: ./dist/WHITELIST-DB.exe
          asset_name: WHITELIST-DB-${{ steps.get_version.outputs.version }}.exe
          asset_content_type: application/octet-stream

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
